const ErrorCode = {
  USER_INPUT_ERROR: 'BAD_USER_INPUT',
  VALIDATION_ERROR: 'VALIDATION_FAILED',
  AUTH_ERROR: 'AUTHENTICATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_SERVER_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
}

export default ErrorCode
